# Generated by Django 4.1 on 2022-09-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Humidity', models.IntegerField()),
                ('Rainfall', models.IntegerField()),
                ('Min_Temp', models.IntegerField()),
                ('Max_Temp', models.IntegerField()),
            ],
        ),
    ]
